// =============================================================================
// queue.js — Song Queue Management (Tauri Version)
// =============================================================================
//
// ORIGINAL (PHP version):
//   queue_array held relative paths like "music/Eighty/Song.mp4".
//   video.src was set directly to these paths (Apache served the files).
//
// NEW (Tauri version):
//   queue_array holds Tauri asset URLs like "https://asset.localhost/C:/...".
//   These are generated by convertFileSrc() in songs.js when building tables.
//   Video src is set to these asset URLs (Tauri's asset protocol serves them).
//
// MEJS LIFECYCLE:
//   The player is created ONCE. Subsequent songs use setSrc() to change
//   the source without destroying the player. resetPlayer() is only called
//   when the queue empties (idle state). See index.js.
// =============================================================================

// Array to hold songs that are queued (same as original)
var queue_array = [];

// ---------------------------------------------------------------------------
// queue_array_create() — Add a song to the queue
// ---------------------------------------------------------------------------
// Called from onclick on song <table> elements (built by songs.js).
// Parameters are the same as original:
//   filename = display name (e.g., "Bohemian Rhapsody")
//   img = thumbnail URL (Tauri asset URL)
//   dir = video file URL (Tauri asset URL)
function queue_array_create(filename, img, dir) {
  // Guard clause: if dir is already in queue_array, display message
  if (queue_array.includes(dir)) {
    var position = queue_array.indexOf(dir) + 1;
    jquery_modal({
      message:
        "This song is already queued at number " +
        position +
        ". Once it is played from the queue, it can be added again.",
      title: "Song Already Queued",
    });
    return;
  }

  // Guard clause: if video.src is same as dir, display message.
  // NOTE: In Tauri, video.src is a full asset URL. We compare directly.
  var currentVideoSrc = document.getElementById("video").src;
  if (currentVideoSrc && currentVideoSrc === dir) {
    jquery_modal({
      message:
        "This song is being played currently. Once it ends completely, it can be re-added to queue.",
      title: "Song Being Played Currently",
    });
    return;
  }

  // Passed guard clauses — add to queue
  queue_array.push(dir);
  var queueNumber = queue_array.length;

  // Build queue item HTML (identical structure to original)
  var queueDiv = document.createElement("div");
  queueDiv.className = "queue_div";
  queueDiv.innerHTML =
    "<div class='queue_top'>" +
    "<img src='" +
    img +
    "'>" +
    "<div class='queue_buttons'>" +
    "<button class='queue_remove_button' onclick='queue_array_remove(this, \"" +
    dir.replace(/"/g, "&quot;") +
    "\")'>Remove <i class='material-icons' id='backspace'>backspace</i></button>" +
    "<button class='queue_movetop_button' onclick='queue_move_to_top(this, \"" +
    dir.replace(/"/g, "&quot;") +
    "\")'>Move to Top <i class='material-icons' id='move_to_top'>vertical_align_top</i></button>" +
    "</div>" +
    "</div>" +
    "<div class='queue_bottom'>" +
    "<span class='queue_number'>" +
    queueNumber +
    ".</span>" +
    "<span class='queue_name'>" +
    filename +
    "</span>" +
    "</div>";
  document.getElementById("right-block-down").appendChild(queueDiv);

  // Scroll to bottom of queue when a song is added
  $("#right-block-down").animate(
    { scrollTop: $("#right-block-down").prop("scrollHeight") },
    500
  );

  // Autoplay: if this is the first song and nothing is playing, start playback
  if (queue_array.length == 1 && $("video").attr("src") == "") {
    play_Queue();
  }
}

// ---------------------------------------------------------------------------
// play_Queue() — Play the next song from the queue
// ---------------------------------------------------------------------------
// KEY CHANGE: Properly destroys the old mejs player before creating a new one.
// In the original, this was the main source of the mejs memory leak.
function play_Queue() {
  // Guard clause: if queue is empty, hand back to shuffle or reset
  if (queue_array.length == 0) {
    // If a shuffle was playing before queue took over, resume it
    if (pendingShuffleRestarter) {
      var restarter = pendingShuffleRestarter;
      pendingShuffleRestarter = null;
      restarter();
      return;
    }

    // No shuffle to resume — reset to idle
    $("#video_title").text("Video Title");
    resetPlayer();

    jquery_modal({
      message:
        "No more songs left in the queue. Click on the thumbnail to add a song in the queue.",
      title: "Queue is Empty",
    });
    return;
  }

  // MEJS FIX: Initialize mejs player with proper lifecycle management.
  // Pass the source URL directly — do NOT set video.src first, because
  // if mejs is already wrapping the video, its setSrc interceptor fires
  // and the URL gets lost before mejs_media_Player can read it.
  mejs_media_Player(play_Queue, queue_array[0]);

  // Update video title from the first queue item's name
  var video_title = document.getElementById("video_title");
  video_title.innerHTML = $("#right-block-down")
    .children(":first")
    .find(".queue_name")
    .text();

  // Remove the played song from queue_array and the DOM
  queue_array.shift();
  var firstQueueItem = $(".queue_div").first();
  firstQueueItem.remove();
  renumber_Queue();
}

// ---------------------------------------------------------------------------
// renumber_Queue() — Update queue item numbers after changes
// ---------------------------------------------------------------------------
function renumber_Queue() {
  $(".queue_number").each(function (i) {
    $(this).text(i + 1 + ".");
  });
}

// ---------------------------------------------------------------------------
// queue_move_to_top() — Move a song to the front of the queue
// ---------------------------------------------------------------------------
function queue_move_to_top(element, dir) {
  var queue_array_index = queue_array.indexOf(dir);

  if (queue_array_index === 0) {
    jquery_modal({
      message: "This song is already at the top of the queue.",
      title: "Already at Top",
    });
    return;
  }

  jquery_modal({
    message:
      "This moves the selected song to the top of the queue. Do you want to proceed?",
    title: "Move Song to Top",
    dialogClass: "show-closer",
    closeTime: 30000,
    buttonText: "Move to Top",
    buttonAction: function () {
      queue_array.splice(queue_array_index, 1);
      queue_array.unshift(dir);
      var queueDiv = $(element).closest(".queue_div");
      queueDiv.prependTo("#right-block-down");
      renumber_Queue();
      $("#right-block-down").animate({ scrollTop: 0 }, 500);
    },
  });
}
